name: ferstar_NoKSU

env:
  KERNEL_SOURCE: 'https://github.com/ferstar/xiaomi_xaga_kernel.git'
  KERNEL_SOURCE_BRANCH: 'mglru'
  KERNEL_DEFCONFIG: 'xaga_defconfig'
  KERNEL_NAME: 'ferstar'
  CLANG_VERSION: 'r416183b1'

on:
#   schedule:
#     - cron: '0 8 * * */5'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Envs
        run: |
          cd $GITHUB_WORKSPACE && mkdir kernel_workspace && cd kernel_workspace
          mkdir android-kernel
          # DIR=`pwd`
          PARENT_DIR=`pwd`
          KERNEL_DIR=`readlink -f ${PARENT_DIR}/android-kernel`

          export CROSS_COMPILE=$PARENT_DIR/clang-r416183b/bin/aarch64-linux-gnu-
          export CC=$PARENT_DIR/clang-r416183b/bin/clang

          export PLATFORM_VERSION=12
          export ANDROID_MAJOR_VERSION=s
          export PATH=$PARENT_DIR/clang-r416183b/bin:$PATH
          export PATH=$PARENT_DIR/build-tools/path/linux-x86:$PATH
          export PATH=$PARENT_DIR/gas/linux-x86:$PATH
          export TARGET_SOC=s5e9925
          export LLVM=1
          export LLVM_IAS=1
          export ARCH=arm64
          export USE_CCACHE=1
          KERNEL_MAKE_ENV="LOCALVERSION=-Android12-9-v$(date +%Y%m%d) CONFIG_LTO_CLANG=y CONFIG_LTO_NONE=n CONFIG_LTO_CLANG_THIN=y CONFIG_LTO_CLANG_FULL=n CONFIG_LOCALVERSION_AUTO=n CONFIG_LOCALVERSION="-ferstart-NoKSU" CONFIG_FB_CFB_IMAGEBLIT=y CONFIG_BUILD_ARM64_KERNEL_COMPRESSION_GZIP=y"

      - name: Download Kernel Source
        run: |
          git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} $KERNEL_DIR --depth=1
      
      - name: Remove KernelSU
        run: |
          cd $KERNEL_DIR
          rm -rf ./KernelSU
          rm -rf ./drivers/kernelsu
          sed -i '/kernelsu/d' $KERNEL_DIR/drivers/Kconfig
          sed -i '/kernelsu/d' $KERNEL_DIR/drivers/Makefile

      - name: Download Clang && Gas && Build_tools
        run: |
          cd $PARENT_DIR
          git clone https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r416183b $PARENT_DIR/clang-r416183b --depth=1
          git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86 $PARENT_DIR/gas/linux-x86 --depth=1
          git clone https://android.googlesource.com/platform/prebuilts/build-tools $PARENT_DIR/build-tools --depth=1
      
      - name: Build Kernel
        run: |
          cd $KERNEL_DIR
          mkdir out
          make CC="ccache clang" CXX="ccache clang++" -j$(nproc) -C $(pwd) $KERNEL_MAKE_ENV gki_defconfig
          make CC="ccache clang" CXX="ccache clang++" -j$(nproc) -C $(pwd) $KERNEL_MAKE_ENV
      
      - name: Pack Kernel
        run: |
          cd $KERNEL_DIR

          mkdir -p tmp

          cp -fp $KERNEL_DIR/arch/arm64/boot/Image.gz tmp
          cp -rp ./anykernel/* tmp

          cd tmp

          7za a -mx9 tmp.zip *

          cd ..

          rm *.zip
          cp -fp tmp/tmp.zip Android12-$(grep "# Linux/" out/.config | cut -d " " -f 3)-v$(date +%Y%m%d-%H).zip
          rm -rf tmp

          # cd $KERNEL_DIR/anykernel
          # cp $KERNEL_DIR/arch/arm64/boot/Image zImage
          # zip -r9 $PARENT_DIR/${VARIANT}_kernel_`date '+%Y_%m_%d'`.zip * -x .git README.md *placeholder
      
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ env.BUILD_TIME }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kernel_workspace/android-kernel/Android12-*.zip
