name: ferstar_NoKSU

env:
  KERNEL_SOURCE: 'https://github.com/ferstar/xiaomi_xaga_kernel.git'
  KERNEL_SOURCE_BRANCH: 'mglru'
  KERNEL_DEFCONFIG: 'xaga_defconfig'
  KERNEL_NAME: 'ferstar'
  CLANG_VERSION: 'r416183b1'

on:
#   schedule:
#     - cron: '0 8 * * */5'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Envs
        run: |
          cd $GITHUB_WORKSPACE && mkdir kernel_workspace && cd kernel_workspace
          # echo "KERNEL_SOURCE=$(cat config.env | grep "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          mkdir android-kernel
          # DIR=`pwd`
          echo "PARENT_DIR=${GITHUB_WORKSPACE}/kernel_workspace" >> $GITHUB_ENV
          echo "KERNEL_DIR=${{ env.PARENT_DIR }}/android-kernel" >> $GITHUB_ENV

          echo "CROSS_COMPILE=${{ env.PARENT_DIR }}/clang-r416183b/bin/aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CC=${{ env.PARENT_DIR }}/clang-r416183b/bin/clang" >> $GITHUB_ENV

          echo "PLATFORM_VERSION=12" >> $GITHUB_ENV
          echo "ANDROID_MAJOR_VERSION=s" >> $GITHUB_ENV
          echo "PATH=${{ env.PARENT_DIR }}/clang-r416183b/bin:$PATH" >> $GITHUB_ENV
          echo "PATH=${{ env.PARENT_DIR }}/build-tools/path/linux-x86:$PATH" >> $GITHUB_ENV
          echo "PATH=${{ env.PARENT_DIR }}/gas/linux-x86:$PATH" >> $GITHUB_ENV
          echo "TARGET_SOC=s5e9925" >> $GITHUB_ENV
          echo "LLVM=1" >> $GITHUB_ENV
          echo "LLVM_IAS=1" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "USE_CCACHE=1" >> $GITHUB_ENV

          KERNEL_MAKE_ENV="LOCALVERSION=-Android12-9-v$(date +%Y%m%d) CONFIG_LTO_CLANG=y CONFIG_LTO_NONE=n CONFIG_LTO_CLANG_THIN=y CONFIG_LTO_CLANG_FULL=n CONFIG_LOCALVERSION_AUTO=n CONFIG_LOCALVERSION=\"-ferstart-NoKSU\" CONFIG_FB_CFB_IMAGEBLIT=y CONFIG_BUILD_ARM64_KERNEL_COMPRESSION_GZIP=y"
          echo "KERNEL_MAKE_ENV=$KERNEL_MAKE_ENV" >> $GITHUB_ENV

      - name: Download Kernel Source
        run: |
          git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} ${{ env.KERNEL_DIR }} --depth=1
      
      - name: Remove KernelSU
        run: |
          cd ${{ env.KERNEL_DIR }}
          ls -l ${{ env.KERNEL_DIR }}
          ls -l ${{ env.KERNEL_DIR }}/drivers  # 添加这一行，用于查看 drivers 目录下的文件
          ls -l ${{ env.KERNEL_DIR }}/drivers/Kconfig  # 添加这一行，用于查看目标文件的信息
          rm -rf ./KernelSU
          rm -rf ./drivers/kernelsu
          sed -i '/kernelsu/d' drivers/Kconfig
          sed -i '/kernelsu/d' drivers/Makefile

      - name: Download Clang && Gas && Build_tools
        run: |
          cd ${{ env.PARENT_DIR }}
          git clone https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r416183b ${{ env.PARENT_DIR }}/clang-r416183b --depth=1
          git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86 ${{ env.PARENT_DIR }}/gas/linux-x86 --depth=1
          git clone https://android.googlesource.com/platform/prebuilts/build-tools ${{ env.PARENT_DIR }}/build-tools --depth=1
      
      - name: Build Kernel
        run: |
          cd ${{ env.KERNEL_DIR }}
          mkdir out
          make CC="ccache clang" CXX="ccache clang++" -j$(nproc) -C $(pwd) ${{ env.KERNEL_MAKE_ENV }} gki_defconfig
          make CC="ccache clang" CXX="ccache clang++" -j$(nproc) -C $(pwd) ${{ env.KERNEL_MAKE_ENV }}
      
      - name: Pack Kernel
        run: |
          cd ${{ env.KERNEL_DIR }}

          mkdir -p tmp

          cp -fp ${{ env.KERNEL_DIR }}/arch/arm64/boot/Image.gz tmp
          cp -rp ./anykernel/* tmp

          cd tmp

          7za a -mx9 tmp.zip *

          cd ..

          rm *.zip
          cp -fp tmp/tmp.zip Android12-$(grep "# Linux/" out/.config | cut -d " " -f 3)-v$(date +%Y%m%d-%H).zip
          rm -rf tmp

          # cd $KERNEL_DIR/anykernel
          # cp $KERNEL_DIR/arch/arm64/boot/Image zImage
          # zip -r9 $PARENT_DIR/${VARIANT}_kernel_`date '+%Y_%m_%d'`.zip * -x .git README.md *placeholder
      
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ env.BUILD_TIME }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kernel_workspace/android-kernel/Android12-*.zip
